# Generated by Django 4.2.5 on 2023-11-28 19:52

import core.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_providers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=core.users.models.get_oauth_providers_default_list, size=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
