# Generated by Django 4.2.5 on 2023-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_oauth_providers_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logout',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
