# Generated by Django 4.2 on 2023-04-09 21:27

import core.speeds.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='description')),
                ('tags', models.TextField(max_length=128, verbose_name='tags')),
                ('speed', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1080000000), core.speeds.validators.CustomMinValueValidator(0)], verbose_name='speed')),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'Downvote'), (0, 'Default State'), (1, 'Upvote')], default=0, verbose_name='vote')),
                ('report', models.TextField(blank=True, choices=[], null=True, verbose_name='report')),
                ('speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speeds.speed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='speed',
            name='feedback',
            field=models.ManyToManyField(related_name='+', through='speeds.SpeedFeedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='speedfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='unique_user_speed'),
        ),
    ]
