# Generated by Django 4.2.5 on 2024-03-17 14:56

import core.speeds.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
                ('speed_type', models.CharField(choices=[('average', 'Average'), ('top', 'Top'), ('constant', 'Constant'), ('relative', 'Relative')], verbose_name='speed type')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=4)),
                ('kmph', models.FloatField(validators=[django.core.validators.MaxValueValidator(1080000000), core.speeds.validators.CustomMinValueValidator(0)], verbose_name='speed in km/h')),
                ('estimated', models.BooleanField(default=False, verbose_name='estimated')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('downvotes', models.PositiveIntegerField(default=0, verbose_name='downvotes')),
                ('upvotes', models.PositiveIntegerField(default=1, verbose_name='upvotes')),
                ('score', models.IntegerField(default=1, verbose_name='score')),
                ('last_synced_to_meilisearch_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced_in_meilisearch', models.BooleanField(default=False)),
                ('added_to_mielisearch_at', models.DateTimeField(blank=True, null=True)),
                ('is_added_to_meilisearch', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'Downvote'), (0, 'Default State'), (1, 'Upvote')], default=0, verbose_name='vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('spam', 'Spam'), ('incorrect data', 'Incorrect Data'), ('non english', 'Non English'), ('inappropriate language', 'Inappropriate Language'), ('other', 'Other')], verbose_name='report reason')),
                ('detail', models.CharField(max_length=256, verbose_name='detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='speeds.speed')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
