# Generated by Django 4.2 on 2023-04-12 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, choices=[('S', 'Spam'), ('I', 'Incorrect Data'), ('NE', 'Non English'), ('IL', 'Inappropriate Language'), ('O', 'Other')], null=True, verbose_name='report')),
                ('other', models.TextField(blank=True, max_length=256, null=True, verbose_name='other')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='speedfeedback',
            name='unique_user_speed',
        ),
        migrations.RenameField(
            model_name='speed',
            old_name='speed',
            new_name='kmph',
        ),
        migrations.RemoveField(
            model_name='speedfeedback',
            name='report',
        ),
        migrations.AddConstraint(
            model_name='speedfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='fb_unique_user_speed'),
        ),
        migrations.AddField(
            model_name='speedreport',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speeds.speed'),
        ),
        migrations.AddField(
            model_name='speedreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedbookmark',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speeds.speed'),
        ),
        migrations.AddField(
            model_name='speedbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='speedreport',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='rp_unique_user_speed'),
        ),
        migrations.AddConstraint(
            model_name='speedbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='bm_unique_user_speed'),
        ),
    ]
