# Generated by Django 4.2.5 on 2023-11-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speedbookmark',
            name='bm_unique_user_speed',
        ),
        migrations.AddConstraint(
            model_name='speedbookmark',
            constraint=models.UniqueConstraint(fields=('category', 'user', 'speed'), name='bm_unique_user_speed'),
        ),
    ]
