# Generated by Django 4.2.5 on 2023-09-14 18:38

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedfeedback',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speeds.speed'),
        ),
        migrations.AddField(
            model_name='speedfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedbookmark',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='speeds.speed'),
        ),
        migrations.AddField(
            model_name='speedbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speed',
            name='feedbacks',
            field=models.ManyToManyField(related_name='+', through='speeds.SpeedFeedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='speedreport',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='rp_unique_user_speed'),
        ),
        migrations.AddConstraint(
            model_name='speedfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='fb_unique_user_speed'),
        ),
        migrations.AddConstraint(
            model_name='speedbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'speed'), name='bm_unique_user_speed'),
        ),
        migrations.AddIndex(
            model_name='speed',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='speeds_spee_tags_cd5226_gin'),
        ),
    ]
