# Generated by Django 4.2.5 on 2023-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0002_remove_speedbookmark_bm_unique_user_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedreport',
            name='detail',
            field=models.CharField(default='fdfdsfa', max_length=256, verbose_name='detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speedreport',
            name='report_reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('incorrect data', 'Incorrect Data'), ('non english', 'Non English'), ('inappropriate language', 'Inappropriate Language'), ('other', 'Other')], default='spam', verbose_name='report reason'),
            preserve_default=False,
        ),
    ]
