# Generated by Django 4.2 on 2023-04-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0002_speedbookmark_speedreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speed',
            old_name='public',
            new_name='is_public',
        ),
    ]
