# Generated by Django 4.2.5 on 2023-10-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0003_speedbookmark_updated_at_speedfeedback_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='added_to_mielisearch_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='is_added_to_meilisearch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speed',
            name='is_synced_in_meilisearch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speed',
            name='last_synced_to_meilisearch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
