# Generated by Django 4.2 on 2023-04-14 19:36

import core.speeds.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speeds', '0003_rename_public_speed_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speed',
            name='kmph',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1080000000), core.speeds.validators.CustomMinValueValidator(0)], verbose_name='kmph speed'),
        ),
        migrations.AlterField(
            model_name='speedfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speedreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
