# Generated by Django 4.2.5 on 2023-11-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0004_speed_added_to_mielisearch_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='added_to_mielisearch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
