# Generated by Django 4.2 on 2023-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0004_alter_speed_author_alter_speed_kmph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='speed_type',
            field=models.TextField(choices=[('AVG', 'Average'), ('TOP', 'Top'), ('CONST', 'Constant'), ('REL', 'Relative')], default='TOP', verbose_name='speed type'),
            preserve_default=False,
        ),
    ]
