# Generated by Django 4.2 on 2023-04-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0006_speed_estimated_alter_speed_kmph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedFeedbackCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvotes', models.PositiveIntegerField(default=0, verbose_name='downvotes')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='upvotes')),
                ('speed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_counter', to='speeds.speed')),
            ],
        ),
    ]
