# Generated by Django 4.2 on 2023-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0007_speedfeedbackcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speed',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='speedbookmark',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='speeds.speed'),
        ),
        migrations.AlterField(
            model_name='speedreport',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='speeds.speed'),
        ),
    ]
