# Generated by Django 4.2 on 2023-08-29 19:01

import core.speeds.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0008_rename_author_speed_user_alter_speedbookmark_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='kmph',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1080000000), core.speeds.validators.CustomMinValueValidator(0)], verbose_name='speed in km/h'),
        ),
    ]
