# Generated by Django 4.2.5 on 2023-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0009_alter_speed_kmph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speed',
            old_name='feedback',
            new_name='feedbacks',
        ),
        migrations.AlterField(
            model_name='speedbookmark',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='category'),
        ),
    ]
