# Generated by Django 4.2.5 on 2023-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0010_rename_feedback_speed_feedbacks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedreport',
            name='other',
        ),
        migrations.RemoveField(
            model_name='speedreport',
            name='report',
        ),
        migrations.AddField(
            model_name='speedreport',
            name='detail',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='speedreport',
            name='report_reason',
            field=models.TextField(blank=True, choices=[('spam', 'Spam'), ('incorrcect data', 'Incorrect Data'), ('non english', 'Non English'), ('inappropriate language', 'Inappropriate Language'), ('other', 'Other')], null=True, verbose_name='report reason'),
        ),
    ]
