# Generated by Django 4.2.5 on 2023-09-13 16:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeds', '0012_speedbookmark_created_at_speedfeedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speed',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='speedbookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='speedfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='speedreport',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='speed',
            name='speed_type',
            field=models.CharField(choices=[('average', 'Average'), ('top', 'Top'), ('constant', 'Constant'), ('relative', 'Relative')], verbose_name='speed type'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tags',
            field=models.CharField(max_length=128, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='speedreport',
            name='detail',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='speedreport',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('incorrcect data', 'Incorrect Data'), ('non english', 'Non English'), ('inappropriate language', 'Inappropriate Language'), ('other', 'Other')], null=True, verbose_name='report reason'),
        ),
        migrations.AddIndex(
            model_name='speed',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='speeds_spee_tags_cd5226_gin'),
        ),
    ]
